CREATE TABLE Users
(
	id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	firstName NVARCHAR(20) NOT NULL,
	lastName NVARCHAR(20) NOT NULL,
	cellPhoneNumber NVARCHAR(MAX) NOT NULL,
	typeOfPromo NVARCHAR(10) NOT NULL,
	entryDate DATETIME NOT NULL DEFAULT GETDATE()
);

